### ISSUE TITLE
Post your GIFs/Screenshots regarding vimpyter

### ISSUE THREAD

**Issue by szymonmaszke** [szymonmaszke/vimpyter#3]
Title says it all, if you have some interesting GIFs/screenshots about vimpyter post them here.

Here are the ones used in README:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/20703378/36789762-f2bca936-1c92-11e8-92f7-c8bf9bede802.gif)

![2018-02-28-142445_1528x880_scrot](https://user-images.githubusercontent.com/20703378/36789826-2e722e42-1c93-11e8-8ec4-2eb3ea399aa3.png)

**Comment by Freed-Wu** [comment]
![Image 7](https://user-images.githubusercontent.com/32936898/71987814-d5508400-3269-11ea-9cae-22308ee5fdb7.png)

Excuse me, how can I run python to get `out[]` in my vim? It looks like I must press `run` in my chrome browser manually and the change in chrome browser will not write to vim?

**Comment by szymonmaszke** [comment]
@Freed-Wu You can't get output in `vim`, only in separate notebook instance (e.g. jupyter notebook in browser). 

When you save your code from vim notebook's data is updated. Reloaded Jupiter tab to see changes.

You __can't__ write to notebook via browser's jupyter, it won't get updated in vim accordingly.
